version: "3.7"
services:
    # App
    app-name:
      build: ./
      image: php:7.4
      container_name: app-name
      environment:
        SERVICE_NAME: app-name
        SERVICE_TAGS: dev
      working_dir: /var/www
      ports:
        - "<port forward>:22"
      tty: true
      volumes:
        - ./:/var/www
        - ./docker/php/php.ini:/usr/local/etc/php/conf.d//php.ini
      networks:
        - app-network
    # Webserver
    nginx-name:
      image: nginx:latest
      container_name: nginx-name
      working_dir: /application
      volumes:
          - ./:/var/www
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "<port forward>:80"
      networks:
       - app-network
      depends_on:
          - app-name
    # DB

    # postgres
    # postgres-name:
    #   image: postgres:latest
    #   container_name: postgres-name
    #   working_dir: /application
    #   volumes:
    #     - "db-data:/var/lib/postgresql/data"
    #   environment:
    #     - POSTGRES_USER=POSTGRES_USER
    #     - POSTGRES_PASSWORD=POSTGRES_PASSWORD
    #     - POSTGRES_DB=POSTGRES_DB
    #   ports:
    #     - "<port forward>:5432"
    #   networks:
    #    - app-network

    # mysql
    # mysql-name:
    #   image: mysql:5.7
    #   command: --default-authentication-plugin=mysql_native_password
    #   container_name: mysql-name
    #   tty: true
    #   ports:
    #     - "<port forward>:3306"
    #   environment:
    #     MYSQL_DATABASE: MYSQL_DATABASE
    #     MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    #     MYSQL_USER: MYSQL_USER
    #     MYSQL_PASSWORD: MYSQL_PASSWORD
    #   volumes:
    #     - db-data:/var/lib/mysql/
    #     - ./docker/mysql/:/etc/mysql/conf.d
    #   networks:
    #     - app-network

networks:
  app-network:
    driver: bridge
volumes:
  db-data:
